import './globals.css'
import Header from "@/app/Header";

export const metadata = {
    title: 'News App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body>
        <div className="main-body">
            <Header/>
            {children}
        </div>
        </body>
        </html>
    )
}
